[functions]
  external_node_modules = ["express", "puppeteer", "dotenv", "cors", "sanitize-html"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
